# Generated by Django 5.1.6 on 2025-02-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('quran', 'Quran Tafsir'), ('hadith', 'Hadith'), ('dua', 'Du’a')], max_length=50)),
                ('content', models.TextField()),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
