# Generated by Django 5.1.6 on 2025-02-24 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Challenge',
            new_name='Challenges',
        ),
    ]
