# Generated by Django 5.1.6 on 2025-02-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizscore',
            name='last_played',
            field=models.DateField(auto_now=True),
        ),
    ]
