# Generated by Django 5.1.6 on 2025-02-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizscore',
            name='fastest_answer_streak',
            field=models.IntegerField(default=0),
        ),
    ]
