# Generated by Django 5.1.6 on 2025-02-23 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalahRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer_name', models.CharField(choices=[('Fajr', 'Fajr'), ('Dhuhr', 'Dhuhr'), ('Asr', 'Asr'), ('Maghrib', 'Maghrib'), ('Isha', 'Isha')], max_length=10)),
                ('status', models.CharField(choices=[('missed', 'Missed'), ('completed', 'Completed')], default='missed', max_length=10)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
